### ISSUE TITLE
Remote Attestation Error on Intel SGX-enabled Machine

### ISSUE THREAD

**Issue by hyunsooda** [openenclave/openenclave#3658]
Hi, I'm trying to test RA on Intel SGX-enabled machine, not ACC.

I followed this doc (https://github.com/openenclave/openenclave/blob/master/docs/GettingStartedDocs/Contributors/NonAccMachineSGXLinuxGettingStarted.md), but RA error still occurred. (There was no error when it ran on ACC)

I put the detailed error msg when I ran `make run` in `sample/attestation` with the flag `OE_LOG_LEVEL=INFO`.

```
 1 host/attestation_host sgxremote ./enclave_a/enclave_a.signed ./enclave_b/enclave_b.signe d
 2 Enclave1: ***../common/crypto.cpp(80): mbedtls initialized.
  3 Enclave2: ***../common/crypto.cpp(80): mbedtls initialized.
  4 Enclave2: ***../common/dispatcher.cpp(80): get_enclave_format_settings
  5 Enclave1: ***../common/dispatcher.cpp(130): get_evidence_with_public_key
  6 Enclave1: ***../common/attestation.cpp(94): oe_serialize_custom_claims
  7 Enclave1: ***../common/attestation.cpp(105): serialized custom claims buffer size: 121
  8 Enclave1: ***../common/attestation.cpp(121): oe_get_evidence failed.(OE_PLATFORM_ERROR)
  9 Enclave1: ***../common/dispatcher.cpp(150): get_evidence_with_public_key failed
 10 Enclave1: ***../common/crypto.cpp(94): mbedtls cleaned up.
 11 Enclave2: ***../common/crypto.cpp(94): mbedtls cleaned up.
 12 Host: Creating two enclaves
 13 Host: Enclave library ./enclave_a/enclave_a.signed
 14 2020-10-12T16:02:27+0900.816042Z [(H)INFO] tid(0x7ff9bc509c00) | Processor supports AVX instructions [/source/host/sgx/linux/xstate.c:_is_xgetbv_supported:33]
 15 2020-10-12T16:02:27+0900.816073Z [(H)INFO] tid(0x7ff9bc509c00) | Value of XFRM to be set in enclave is 7
 16  [/source/host/sgx/sgxload.c:_detect_xfrm:121]
 17 2020-10-12T16:02:27+0900.818675Z [(H)INFO] tid(0x7ff9bc509c00) | Loading libsgx_enclave_common.so.1
 18  [/source/host/sgx/sgx_enclave_common_wrapper.c:_load_sgx_enclave_common_impl:110]
 19 2020-10-12T16:02:27+0900.818747Z [(H)INFO] tid(0x7ff9bc509c00) | Loaded libsgx_enclave_common.so.1
 20  [/source/host/sgx/sgx_enclave_common_wrapper.c:_load_sgx_enclave_common_impl:126]
 21 2020-10-12T16:02:27+0900.935639Z [(H)WARN] tid(0x7ff9bc509c00) | In-enclave logging is not supported. To enable, please add 
 22 
 23 from "openenclave/edl/logging.edl" import *;
 24 
 25 in the edl file.
 26  [/source/host/sgx/create.c:oe_create_enclave:1014]
 27 Host: Enclave successfully created.
 28 Host: Enclave library ./enclave_b/enclave_b.signed
 29 2020-10-12T16:02:27+0900.935648Z [(H)INFO] tid(0x7ff9bc509c00) | Processor supports AVX instructions [/source/host/sgx/linux/xstate.c:_is_xgetbv_supported:33]
 30 2020-10-12T16:02:27+0900.935650Z [(H)INFO] tid(0x7ff9bc509c00) | Value of XFRM to be set in enclave is 7
 31  [/source/host/sgx/sgxload.c:_detect_xfrm:121]
 32 2020-10-12T16:02:28+0900.131996Z [(H)WARN] tid(0x7ff9bc509c00) | In-enclave logging is not supported. To enable, please add 
 33 
 34 from "openenclave/edl/logging.edl" import *;
 35 
 36 in the edl file.
 37  [/source/host/sgx/create.c:oe_create_enclave:1014]
 38 Host: Enclave successfully created.
 39 
 40 
 41 Host: ********** Attest enclave_a to enclave_b **********
 42 
 43 Host: Requesting enclave_b format settings
 44 Host: Requesting enclave_a to generate a targeted evidence with an encryption key
 45 2020-10-12T16:02:28+0900.132093Z [(H)INFO] tid(0x7ff9bc509c00) | Loading libsgx_dcap_ql.so
 46  [/source/host/sgx/sgxquote.c:_load_sgx_dcap_ql_impl:131]
 47 2020-10-12T16:02:28+0900.132337Z [(H)INFO] tid(0x7ff9bc509c00) | Loaded libsgx_dcap_ql.so
 48  [/source/host/sgx/sgxquote.c:_load_sgx_dcap_ql_impl:145]
 49 2020-10-12T16:02:28+0900.132341Z [(H)INFO] tid(0x7ff9bc509c00) | DCAP installed and set for in-process quoting. [/source/host/sgx/sgxquote.c:_load_quote_ex_library_once:178]
 50 2020-10-12T16:02:28+0900.132348Z [(H)INFO] tid(0x7ff9bc509c00) | DCAP only supports ECDSA_P256
 51  [/source/host/sgx/sgxquote.c:oe_sgx_get_supported_attester_format_ids:619]
 52 2020-10-12T16:02:28+0900.132382Z [(H)INFO] tid(0x7ff9bc509c00) | oe_load_quote_provider libdcap_quoteprov.so
 53  [/source/host/sgx/linux/sgxquoteproviderloader.c:oe_load_quote_provider:25]
 54 2020-10-12T16:02:28+0900.136236Z [(H)WARN] tid(0x7ff9bc509c00) | sgxquoteprovider: sgx_ql_set_logging_function not found
 55  [/source/host/sgx/linux/sgxquoteproviderloader.c:oe_load_quote_provider:46]
 56 2020-10-12T16:02:28+0900.136240Z [(H)INFO] tid(0x7ff9bc509c00) | sgxquoteprovider: provider.get_sgx_quote_verification_collateral = 0x7ff9bc47c7c0
 57  [/source/host/sgx/linux/sgxquoteproviderloader.c:oe_load_quote_provider:59]
 58 2020-10-12T16:02:28+0900.136241Z [(H)INFO] tid(0x7ff9bc509c00) | sgxquoteprovider: provider.get_sgx_quote_verification_collateral = 0x7ff9bc47c700
 59  [/source/host/sgx/linux/sgxquoteproviderloader.c:oe_load_quote_provider:64]
 60 2020-10-12T16:02:28+0900.154055Z [(H)ERROR] tid(0x7ff9bc509c00) | quote3_error_t=0xe035
 61  (oe_result_t=OE_PLATFORM_ERROR) [/source/host/sgx/sgxquote.c:oe_sgx_qe_get_target_info:401]
 62 2020-10-12T16:02:28+0900.154060Z [(H)ERROR] tid(0x7ff9bc509c00) | :OE_PLATFORM_ERROR [/source/host/sgx/quote.c:sgx_get_qetarget_info:37]
 63 Host: get_evidence_with_public_key failed. OE_OK
 64 Host: attestation failed with 1
 65 Host: Terminating enclaves
 66 Host: Enclave successfully terminated.
 67 Host: Enclave successfully terminated.
 68 Host:  failed 
 69 2020-10-12T16:02:28+0900.162239Z [(H)INFO] tid(0x7ff9bc509c00) | _unload_quote_provider libdcap_quoteprov.so
 70  [/source/host/sgx/linux/sgxquoteproviderloader.c:_unload_quote_provider:13]
 71 Makefile:24: recipe for target 'runsgxremote' failed

```
In this log, the `libdcap_quoteprov.so` library successfully loaded but it says that it supports only the ECDSA scheme which is supported by IAS. `oesign` accepts only keys based on the RSA scheme. So I'm guessing this mismatch is the root cause of the error. 

I was just wondering how the author can attest by following instructions in the doc that describes remote attestation on Non-ACC.

**Comment by shnwc** [comment]
The RSA keys used by `oesign` to sign enclave images are unrelated to the ECDSA keys in evidenced for remote attestation.

The log line 49 indicates that DCAP in-process quoting is used, and line 60 indicates that the application has not been setup with sufficient privilege for in-process quoting. Please make sure the instructions in the [DCAP README](https://github.com/intel/SGXDataCenterAttestationPrimitives/blob/master/QuoteGeneration/README.md#build-and-install-intelr-sgx-driver) are followed to add the enclave user to the right group.

**Comment by hyunsooda** [comment]
Hi @shnwc :smile: 

I added user account to `sgx_prv` and the error occurred still. Let me attach libraries installed.
```
  1 ii  libsgx-ae-le                               2.11.100.2-bionic1                               amd64        Intel(R) Software Guard Extensions LE
  2 ii  libsgx-ae-pce                              2.11.100.2-bionic1                               amd64        Intel(R) Software Guard Extensions PCE
  3 ii  libsgx-ae-qe3                              1.8.100.2-bionic1                                amd64        Intel(R) Software Guard Extensions QE3
  4 ii  libsgx-ae-qve                              1.8.100.2-bionic1                                amd64        Intel(R) Software Guard Extensions QVE
  5 ii  libsgx-aesm-launch-plugin                  2.11.100.2-bionic1                               amd64        Launch Plugin for Intel(R) Software Guard Extensions AESM Service
  6 ii  libsgx-dcap-default-qpl                    1.8.100.2-bionic1                                amd64        Intel(R) Software Guard Extensions Default Quote Provider Library
  7 ii  libsgx-dcap-ql                             1.8.100.2-bionic1                                amd64        Intel(R) Software Guard Extensions Data Center Attestation Primitives
  8 ii  libsgx-dcap-ql-dev                         1.8.100.2-bionic1                                amd64        Intel(R) Software Guard Extensions Data Center Attestation Primitives For Developers
  9 ii  libsgx-dcap-quote-verify                   1.8.100.2-bionic1                                amd64        Intel(R) Software Guard Extensions Data Center Attestation Primitives
 10 ii  libsgx-enclave-common                      2.11.100.2-bionic1                               amd64        Intel(R) Software Guard Extensions Enclave Common Loader
 11 ii  libsgx-enclave-common-dev                  2.11.100.2-bionic1                               amd64        Intel(R) Software Guard Extensions Enclave Common Loader for Developers
 12 ii  libsgx-launch                              2.11.100.2-bionic1                               amd64        Intel(R) Software Guard Extensions Launch Service
 13 ii  libsgx-pce-logic                           1.8.100.2-bionic1                                amd64        Intel(R) Software Guard Extensions Data Center Attestation Primitives
 14 ii  libsgx-qe3-logic                           1.8.100.2-bionic1                                amd64        Intel(R) Software Guard Extensions Data Center Attestation Primitives
 15 ii  libsgx-urts                                2.11.100.2-bionic1                               amd64        Intel(R) Software Guard Extensions uRTS
 16 ii  sgx-aesm-service                           2.11.100.2-bionic1                               amd64        Intel(R) Software Guard Extensions AESM Service
 17 ii  sgx-dcap-pccs                              1.8.100.2-bionic1                                amd64        Intel(R) Software Guard Extensions PCK Caching Service
```
I'm sure that necessary libraries are installed to run remote attestation. Is there some point in configuration or installation that I'm missing?

Thank you

**Comment by hyjiang** [comment]
Are you running the test in guest VM? if it's the case, then pls make sure you using `root` or user in `sgx_prv` group to launch the VM.

**Comment by hyunsooda** [comment]
Hi @hyjiang, 

No, I was not using VM when testing the RA.

**Comment by shnwc** [comment]
When  you run "groups" command, is "sgx_prv" listed as one of the groups? Can you follow the suggestions in log lines 21 and 32 to enable in-enclave logging, and re-run the tests and see what the logs show?

**Comment by hyunsooda** [comment]
Sure,

```
  1 host/attestation_host sgxremote ./enclave_a/enclave_a.signed ./enclave_b/enclave_b.signed
  2 Enclave1: ***../common/crypto.cpp(80): mbedtls initialized.
  3 Enclave2: ***../common/crypto.cpp(80): mbedtls initialized.
  4 Enclave2: ***../common/dispatcher.cpp(80): get_enclave_format_settings
  5 Enclave1: ***../common/dispatcher.cpp(130): get_evidence_with_public_key
  6 Enclave1: ***../common/attestation.cpp(94): oe_serialize_custom_claims
  7 Enclave1: ***../common/attestation.cpp(105): serialized custom claims buffer size: 121
  8 Host: Creating two enclaves
  9 Host: Enclave library ./enclave_a/enclave_a.signed
 10 2020-10-15T10:22:56+0900.459037Z [(H)INFO] tid(0x7f84b5642c00) | Processor supports AVX instructions [/source/host/sgx/linux/xstate.c:_is_xgetbv_supported:33]
 11 2020-10-15T10:22:56+0900.459175Z [(H)INFO] tid(0x7f84b5642c00) | Value of XFRM to be set in enclave is 7
 12  [/source/host/sgx/sgxload.c:_detect_xfrm:121]
 13 2020-10-15T10:22:56+0900.470945Z [(H)INFO] tid(0x7f84b5642c00) | Loading libsgx_enclave_common.so.1
 14  [/source/host/sgx/sgx_enclave_common_wrapper.c:_load_sgx_enclave_common_impl:110]
 15 2020-10-15T10:22:56+0900.471196Z [(H)INFO] tid(0x7f84b5642c00) | Loaded libsgx_enclave_common.so.1
 16  [/source/host/sgx/sgx_enclave_common_wrapper.c:_load_sgx_enclave_common_impl:126]
 17 Host: Enclave successfully created.
 18 Host: Enclave library ./enclave_b/enclave_b.signed
 19 2020-10-15T10:22:56+0900.669173Z [(H)INFO] tid(0x7f84b5642c00) | Processor supports AVX instructions [/source/host/sgx/linux/xstate.c:_is_xgetbv_supported:33]
 20 2020-10-15T10:22:56+0900.669181Z [(H)INFO] tid(0x7f84b5642c00) | Value of XFRM to be set in enclave is 7
 21  [/source/host/sgx/sgxload.c:_detect_xfrm:121]
 22 Host: Enclave successfully created.
 23 
 24 
 25 Host: ********** Attest enclave_a to enclave_b **********
 26 
 27 Host: Requesting enclave_b format settings
 28 2020-10-15T10:22:56+0900.812357Z [(E)INFO] tid(0x7f84b5642c00) | enclave_b.signed:got verifiers_length=4 plugins [/source/common/sgx/verifier.c:oe_verifier_initialize:904]
 29 Host: Requesting enclave_a to generate a targeted evidence with an encryption key
 30 2020-10-15T10:22:56+0900.812426Z [(H)INFO] tid(0x7f84b5642c00) | Loading libsgx_dcap_ql.so
 31  [/source/host/sgx/sgxquote.c:_load_sgx_dcap_ql_impl:131]
 32 2020-10-15T10:22:56+0900.812656Z [(H)INFO] tid(0x7f84b5642c00) | Loaded libsgx_dcap_ql.so
 33  [/source/host/sgx/sgxquote.c:_load_sgx_dcap_ql_impl:145]
 34 2020-10-15T10:22:56+0900.812659Z [(H)INFO] tid(0x7f84b5642c00) | DCAP installed and set for in-process quoting. [/source/host/sgx/sgxquote.c:_load_quote_ex_library_once:178]
 35 2020-10-15T10:22:56+0900.812667Z [(H)INFO] tid(0x7f84b5642c00) | DCAP only supports ECDSA_P256
 36  [/source/host/sgx/sgxquote.c:oe_sgx_get_supported_attester_format_ids:619]
 37 2020-10-15T10:22:56+0900.812679Z [(E)INFO] tid(0x7f84b5642c00) | enclave_a.signed:uuid_count=1 [/source/enclave/sgx/attester.c:_get_attester_plugins:386]
 38 2020-10-15T10:22:56+0900.812687Z [(E)INFO] tid(0x7f84b5642c00) | enclave_a.signed:got attesters_length=2 plugins [/source/enclave/sgx/attester.c:oe_attester_initialize:457]
 39 2020-10-15T10:22:56+0900.812720Z [(H)INFO] tid(0x7f84b5642c00) | oe_load_quote_provider libdcap_quoteprov.so
 40  [/source/host/sgx/linux/sgxquoteproviderloader.c:oe_load_quote_provider:25]
 41 2020-10-15T10:22:56+0900.816540Z [(H)WARN] tid(0x7f84b5642c00) | sgxquoteprovider: sgx_ql_set_logging_function not found
 42  [/source/host/sgx/linux/sgxquoteproviderloader.c:oe_load_quote_provider:46]
 43 2020-10-15T10:22:56+0900.816544Z [(H)INFO] tid(0x7f84b5642c00) | sgxquoteprovider: provider.get_sgx_quote_verification_collateral = 0x7f84b55b57c0
 44  [/source/host/sgx/linux/sgxquoteproviderloader.c:oe_load_quote_provider:59]
 45 2020-10-15T10:22:56+0900.816545Z [(H)INFO] tid(0x7f84b5642c00) | sgxquoteprovider: provider.get_sgx_quote_verification_collateral = 0x7f84b55b5700
 46  [/source/host/sgx/linux/sgxquoteproviderloader.c:oe_load_quote_provider:64]
 47 2020-10-15T10:22:56+0900.833518Z [(H)ERROR] tid(0x7f84b5642c00) | quote3_error_t=0xe035
 48  (oe_result_t=OE_PLATFORM_ERROR) [/source/host/sgx/sgxquote.c:oe_sgx_qe_get_target_info:401]
 49 2020-10-15T10:22:56+0900.833523Z [(H)ERROR] tid(0x7f84b5642c00) | :OE_PLATFORM_ERROR [/source/host/sgx/quote.c:sgx_get_qetarget_info:37]
 50 2020-10-15T10:22:56+0900.833538Z [(E)ERROR] tid(0x7f84b5642c00) | enclave_a.signed::OE_PLATFORM_ERROR [/source/enclave/core/sgx/report.c:oe_get_remote_report:279]
 51 2020-10-15T10:22:56+0900.833545Z [(E)ERROR] tid(0x7f84b5642c00) | enclave_a.signed::OE_PLATFORM_ERROR [/source/enclave/core/sgx/report.c:_oe_get_report_internal:384]
 52 2020-10-15T10:22:56+0900.833551Z [(E)ERROR] tid(0x7f84b5642c00) | enclave_a.signed::OE_PLATFORM_ERROREnclave1: ***../common/attestation.cpp(121): oe_get_evidence failed.(OE_PLATFORM_ERROR)
 53 Enclave1: ***../common/dispatcher.cpp(150): get_evidence_with_public_key failed
 54 Enclave1: ***../common/crypto.cpp(94): mbedtls cleaned up.
 55 Enclave2: ***../common/crypto.cpp(94): mbedtls cleaned up.
 56  [/source/enclave/core/sgx/report.c:oe_get_report_v2_internal:439]
 57 2020-10-15T10:22:56+0900.833574Z [(E)ERROR] tid(0x7f84b5642c00) | enclave_a.signed:SGX Plugin: Failed to get OE report. OE_PLATFORM_ERROR (oe_result_t=OE_PLATFORM_ERROR) [/source/enclave/sgx/attester.c:_get_evidence:173]
 58 2020-10-15T10:22:56+0900.833580Z [(E)ERROR] tid(0x7f84b5642c00) | enclave_a.signed::OE_PLATFORM_ERROR [/source/enclave/attest_plugin.c:oe_get_evidence:116]
 59 Host: get_evidence_with_public_key failed. OE_OK
 60 Host: attestation failed with 1
 61 Host: Terminating enclaves
 62 2020-10-15T10:22:56+0900.833658Z [(E)INFO] tid(0x7f84b5642c00) | enclave_a.signed:free attesters_length=2 plugins [/source/enclave/sgx/attester.c:oe_attester_shutdown:490]
 63 2020-10-15T10:22:56+0900.833666Z [(E)INFO] tid(0x7f84b5642c00) | enclave_a.signed:verifiers is NULL [/source/common/sgx/verifier.c:oe_verifier_shutdown:930]
 64 Host: Enclave successfully terminated.
 65 2020-10-15T10:22:56+0900.837752Z [(E)INFO] tid(0x7f84b5642c00) | enclave_b.signed:attesters is NULL [/source/enclave/sgx/attester.c:oe_attester_shutdown:485]
 66 2020-10-15T10:22:56+0900.837761Z [(E)INFO] tid(0x7f84b5642c00) | enclave_b.signed:free verifiers_length=4 plugins [/source/common/sgx/verifier.c:oe_verifier_shutdown:935]
 67 Host: Enclave successfully terminated.
 68 Host:  failed 
 69 2020-10-15T10:22:56+0900.841715Z [(H)INFO] tid(0x7f84b5642c00) | _unload_quote_provider libdcap_quoteprov.so
 70  [/source/host/sgx/linux/sgxquoteproviderloader.c:_unload_quote_provider:13]
 71 Makefile:24: recipe for target 'runsgxremote' failed
```

It seems to be added a call trace for getting report and others are the same before.

**Comment by jdbeaney** [comment]
Which SGX driver do you have installed?  /dev/sgx or /dev/isgx?

**Comment by hyunsooda** [comment]
Hi @jdbeaney,

I have two machines, one displays `/dev/sgx` another one displays `/dev/isgx` and both show the same quote error.

**Comment by hyunsooda** [comment]
I have a new machine which is equipped with a list below.

- Xeon E-2200 series
- /dev/sgx
- AESNI is enabled

The error logs are the exactly same as before. Can I know about your environments or configuration for RA on Openenclave?

**Comment by jdbeaney** [comment]
What OS are you running?

Can you add the the user running the code the "sgx_prv" group?
sudo usermod -a -G sgx_prv <user name>

**Comment by hyunsooda** [comment]
Yes, I added a user who runs RA into `sgx_prv` and I was testing in Ubuntu 18.04.

**Comment by jdbeaney** [comment]
OK.  And you are still seeing the Privilege error in the logs (0xe035)?
SGX_QL_ERROR_INVALID_PRIVILEGE = SGX_QL_MK_ERROR(0x0035)

 46  [/source/host/sgx/linux/sgxquoteproviderloader.c:oe_load_quote_provider:64]
 47 2020-10-15T10:22:56+0900.833518Z [(H)ERROR] tid(0x7f84b5642c00) | quote3_error_t=0xe035

**Comment by hyunsooda** [comment]
Currently, the error log is `2020-10-31T14:02:56-0400.834394Z [(H)ERROR] tid(0x7f10bea66c00) | quote3_error_t=0xe011`
(SGX_QL_NO_PLATFORM_CERT_DATA = SGX_QL_MK_ERROR(0x0011)).

The name defined for the log seems to be implicit that I have to make a certificate from Intel.  Isn't it?
Thanks for helping me.

**Comment by jdbeaney** [comment]
This error (SGX_QL_NO_PLATFORM_CERT_DATA = 0xE011) means that the PCK Certificate for your platform is not available from the caching service (PCCS).  Can you check you PCCS configuration and QPL configuration matches the doc here:  https://github.com/openenclave/openenclave/blob/master/docs/GettingStartedDocs/Contributors/NonAccMachineSGXLinuxGettingStarted.md


If the configuration is correct, can you provide the PCCS logs following the information in this doc:  https://download.01.org/intel-sgx/sgx-dcap/1.8/linux/docs/SGX_DCAP_Caching_Service_Design_Guide_0.5.pdf

in section 6:
LogLevel: 
Use the same levels as npm: error, warn, info, http, verbose, debug, silly. Default is
info. Log messages are written to <PCCS Install Directory>/logs/pccs server.log.

**Comment by hyunsooda** [comment]
- PCCS is running via pm2 on the `pccs` user
- Still can fetch rootcrl with this command `curl --noproxy "*" -v -k -G "https://localhost:8081/sgx/certification/v2/rootcacrl"`
- Still failed remote attestation, please see the following logs (log level was set to `info`)

0|pccs     | 2020-11-04 20:39:58.387 [error]: Error: No cache data for this platform.
0|pccs     |     at Object.exports.pckCertSelection (/opt/intel/sgx-dcap-pccs/services/pckcertService.js:227:15)
0|pccs     |     at async Object.exports.getPckCert (/opt/intel/sgx-dcap-pccs/services/pckcertService.js:271:22)
0|pccs     |     at async exports.getPckCert (/opt/intel/sgx-dcap-pccs/controllers/pckcertController.js:66:29)
0|pccs     | 2020-11-04 20:39:58.390 [info]: 127.0.0.1 - - [05/Nov/2020:01:39:58 +0000] "GET /sgx/certification/v2/pckcert?qeid=....&encrypted_ppid=....&cpusvn=0006FFFFFFFF00000000000000000000&pcesvn=0A00&pceid=0000 HTTP/1.1" 404 32 "-" "-"

**Comment by jdbeaney** [comment]
Can you change the PCCS logging level to 'silly' and provide the logs?

**Comment by hyunsooda** [comment]
Uhm, the log is same as before although the logging level was changed to `silly`.

**Comment by jdbeaney** [comment]
Looking at you CPUSVN (cpusvn=0006FFFFFFFF00000000000000000000) it looks like you have an older BIOS.  Can you get an updated BIOS from your OEM vendor?  The problem is that the uCode patch is not loaded at reset.

**Comment by hyunsooda** [comment]
I updated the BIOS and saw some changed log.

Before update BIOS:
- `cpusvn=0006FFFFFFFF00000000000000000000&pcesvn=0A00&pceid=0000`
After update BIOS:
- `cpusvn=0010FFFFFFFF00000000000000000000&pcesvn=0A00&pceid=0000`

How I know that whether the represented bios number is outdated or not?

**Comment by jdbeaney** [comment]
The CPUSVN value is non-architecturally defined.  Meaning, it can change definition over time.  From your latest data, I can see that you updated your BIOS but the BIOS is still not loading the uCode patch at reset.  I have seen this problem with HP platforms before.  Do they have an SGX capable BIOS that you can apply to this platform?

**Comment by hyunsooda** [comment]
Yes, I'm using HPE server platform and I couldn't find SGX capable BIOS in the online service center, where I found latest bios patch. It seems that there is no information about this problem. Can I know about your server or desktop envrionment(Platform, CPU, OS, etc)?

**Comment by hyunsooda** [comment]
Hi @jdbeaney, @shnwc. I solved this problem on another platform and is working well now. Let me close this issue.
