### ISSUE TITLE
Memory leak in helloworld example found by ASAN

### ISSUE THREAD

**Issue by LuminousXLB** [openenclave/openenclave#4028]
## Environment

- Open Enclave v0.15.0
- clang version 8.0.0-3~ubuntu18.04.2

## What I did

Append the following rules to `host/CMakeLists.txt`

```
target_compile_options(helloworld_host PRIVATE "-fsanitize=address" "-fno-omit-frame-pointer")
target_link_options(helloworld_host PRIVATE "-fsanitize=address" "-fno-omit-frame-pointer")
```

Build and Run

``` console
ubuntu@adbe032032ea:~/helloworld/build$ cmake ..
-- The C compiler identification is Clang 8.0.0
-- The CXX compiler identification is Clang 8.0.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/clang-8 - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/clang++-8 - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Looking for crypto library - found
-- Looking for dl library - found
-- Performing Test OE_SPECTRE_MITIGATION_C_FLAGS_SUPPORTED
-- Performing Test OE_SPECTRE_MITIGATION_C_FLAGS_SUPPORTED - Success
-- Performing Test OE_SPECTRE_MITIGATION_CXX_FLAGS_SUPPORTED
-- Performing Test OE_SPECTRE_MITIGATION_CXX_FLAGS_SUPPORTED - Success
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ubuntu/helloworld/build
ubuntu@adbe032032ea:~/helloworld/build$ make run
[ 10%] Generating helloworld_t.h, helloworld_t.c, helloworld_args.h
Generating edge routine, for the Open Enclave SDK.
Processing /home/ubuntu/helloworld/helloworld.edl.
Processing /opt/openenclave/include/openenclave/edl/syscall.edl.
Processing /opt/openenclave/include/openenclave/edl/epoll.edl.
Processing /opt/openenclave/include/openenclave/edl/fcntl.edl.
Processing /opt/openenclave/include/openenclave/edl/ioctl.edl.
Processing /opt/openenclave/include/openenclave/edl/poll.edl.
Processing /opt/openenclave/include/openenclave/edl/signal.edl.
Processing /opt/openenclave/include/openenclave/edl/socket.edl.
Processing /opt/openenclave/include/openenclave/edl/time.edl.
Processing /opt/openenclave/include/openenclave/edl/unistd.edl.
Processing /opt/openenclave/include/openenclave/edl/utsname.edl.
Processing /opt/openenclave/include/openenclave/edl/sgx/platform.edl.
Processing /opt/openenclave/include/openenclave/edl/sgx/attestation.edl.
Processing /opt/openenclave/include/openenclave/edl/sgx/cpu.edl.
Processing /opt/openenclave/include/openenclave/edl/sgx/debug.edl.
Processing /opt/openenclave/include/openenclave/edl/sgx/thread.edl.
Processing /opt/openenclave/include/openenclave/edl/sgx/switchless.edl.
Success.
Scanning dependencies of target enclave
[ 20%] Building C object enclave/CMakeFiles/enclave.dir/enc.c.o
[ 30%] Building C object enclave/CMakeFiles/enclave.dir/helloworld_t.c.o
[ 40%] Linking C executable enclave
[ 40%] Built target enclave
Scanning dependencies of target sign
[ 50%] Generating private.pem, public.pem
Generating RSA private key, 3072 bit long modulus (2 primes)
........................................................................++++
.++++
e is 3 (0x03)
writing RSA key
[ 60%] Generating enclave/enclave.signed
Created /home/ubuntu/helloworld/build/enclave/enclave.signed
[ 60%] Built target sign
[ 70%] Generating helloworld_u.h, helloworld_u.c, helloworld_args.h
Generating edge routine, for the Open Enclave SDK.
Processing /home/ubuntu/helloworld/helloworld.edl.
Processing /opt/openenclave/include/openenclave/edl/syscall.edl.
Processing /opt/openenclave/include/openenclave/edl/epoll.edl.
Processing /opt/openenclave/include/openenclave/edl/fcntl.edl.
Processing /opt/openenclave/include/openenclave/edl/ioctl.edl.
Processing /opt/openenclave/include/openenclave/edl/poll.edl.
Processing /opt/openenclave/include/openenclave/edl/signal.edl.
Processing /opt/openenclave/include/openenclave/edl/socket.edl.
Processing /opt/openenclave/include/openenclave/edl/time.edl.
Processing /opt/openenclave/include/openenclave/edl/unistd.edl.
Processing /opt/openenclave/include/openenclave/edl/utsname.edl.
Processing /opt/openenclave/include/openenclave/edl/sgx/platform.edl.
Processing /opt/openenclave/include/openenclave/edl/sgx/attestation.edl.
Processing /opt/openenclave/include/openenclave/edl/sgx/cpu.edl.
Processing /opt/openenclave/include/openenclave/edl/sgx/debug.edl.
Processing /opt/openenclave/include/openenclave/edl/sgx/thread.edl.
Processing /opt/openenclave/include/openenclave/edl/sgx/switchless.edl.
Success.
Scanning dependencies of target helloworld_host
[ 80%] Building C object host/CMakeFiles/helloworld_host.dir/host.c.o
[ 90%] Building C object host/CMakeFiles/helloworld_host.dir/helloworld_u.c.o
[100%] Linking C executable helloworld_host
[100%] Built target helloworld_host
Scanning dependencies of target run
Hello world from the enclave
Enclave called into host to print: Hello World!

=================================================================
==20893==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 16384 byte(s) in 1 object(s) allocated from:
    #0 0x4c9ce3 in __interceptor_malloc (/home/ubuntu/helloworld/build/host/helloworld_host+0x4c9ce3)
    #1 0x56f30f in _setup_ecall_context /source/openenclave/host/sgx/enter.c:143:33
    #2 0x56f30f in __morestack /source/openenclave/host/sgx/enter.c:189
    #3 0x565cb0 in _do_eenter /source/openenclave/host/sgx/calls.c:193:13
    #4 0x565cb0 in oe_ecall /source/openenclave/host/sgx/calls.c:612

SUMMARY: AddressSanitizer: 16384 byte(s) leaked in 1 allocation(s).
CMakeFiles/run.dir/build.make:76: recipe for target 'CMakeFiles/run' failed
make[3]: *** [CMakeFiles/run] Error 1
CMakeFiles/Makefile2:166: recipe for target 'CMakeFiles/run.dir/all' failed
make[2]: *** [CMakeFiles/run.dir/all] Error 2
CMakeFiles/Makefile2:173: recipe for target 'CMakeFiles/run.dir/rule' failed
make[1]: *** [CMakeFiles/run.dir/rule] Error 2
Makefile:150: recipe for target 'run' failed
make: *** [run] Error 2
```

**Comment by anakrish** [comment]
@mrragava @mingweishih  Does ASAN work out of the box with OE enclaves?

**Comment by mrragava** [comment]
No, ASAN is not compatible with enclave binaries. This is reported on host binary anyway.
